# Generated by Django 5.0.2 on 2024-02-21 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_timeslot_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
    ]
