# Generated by Django 5.0.2 on 2024-02-21 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_remove_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='booked_at',
            field=models.DateField(),
        ),
    ]
